#!/usr/bin/env python3
"""
Flask API demonstrating Basic Authentication, JWT Authentication,
and role-based authorization.

This module implements:
- Basic HTTP Authentication using Flask-HTTPAuth
- JWT-based authentication using Flask-JWT-Extended
- Role-based access control for admin-only routes
"""

from flask import Flask, jsonify, request
from flask_httpauth import HTTPBasicAuth
from flask_jwt_extended import (
    JWTManager,
    create_access_token,
    jwt_required,
    get_jwt
)
from werkzeug.security import generate_password_hash, check_password_hash


app = Flask(__name__)

# Secret key used to sign and verify JWT tokens
app.config["JWT_SECRET_KEY"] = "super-secret-key"

auth = HTTPBasicAuth()
jwt = JWTManager(app)


users = {
    "user1": {
        "username": "user1",
        "password": generate_password_hash("password"),
        "role": "user"
    },
    "admin1": {
        "username": "admin1",
        "password": generate_password_hash("password"),
        "role": "admin"
    }
}


@auth.verify_password
def verify_password(username, password):
    """
    Verify username and password for Basic Authentication.

    Args:
        username (str): The username provided by the client.
        password (str): The password provided by the client.

    Returns:
        str or None: The username if credentials are valid, otherwise None.
    """
    user = users.get(username)

    if user and check_password_hash(user["password"], password):
        return username

    return None


@auth.error_handler
def basic_auth_error(status):
    """
    Handle Basic Authentication errors.

    Args:
        status (int): HTTP status code generated by Flask-HTTPAuth.

    Returns:
        tuple: JSON error response with 401 status code.
    """
    return jsonify({"error": "Unauthorized"}), 401


@app.route("/basic-protected")
@auth.login_required
def basic_protected():
    """
    Protected route using Basic Authentication.

    Returns:
        str: Access granted message if Basic Auth credentials are valid.
    """
    return "Basic Auth: Access Granted"


@jwt.unauthorized_loader
def handle_unauthorized_error(err):
    """
    Handle missing JWT token errors.

    Args:
        err (str): Error message from Flask-JWT-Extended.

    Returns:
        tuple: JSON error response with 401 status code.
    """
    return jsonify({"error": "Missing or invalid token"}), 401


@jwt.invalid_token_loader
def handle_invalid_token_error(err):
    """
    Handle invalid or malformed JWT token errors.

    Args:
        err (str): Error message from Flask-JWT-Extended.

    Returns:
        tuple: JSON error response with 401 status code.
    """
    return jsonify({"error": "Invalid token"}), 401


@jwt.expired_token_loader
def handle_expired_token_error(jwt_header, jwt_payload):
    """
    Handle expired JWT token errors.

    Args:
        jwt_header (dict): JWT header data.
        jwt_payload (dict): JWT payload data.

    Returns:
        tuple: JSON error response with 401 status code.
    """
    return jsonify({"error": "Token has expired"}), 401


@jwt.revoked_token_loader
def handle_revoked_token_error(jwt_header, jwt_payload):
    """
    Handle revoked JWT token errors.

    Args:
        jwt_header (dict): JWT header data.
        jwt_payload (dict): JWT payload data.

    Returns:
        tuple: JSON error response with 401 status code.
    """
    return jsonify({"error": "Token has been revoked"}), 401


@jwt.needs_fresh_token_loader
def handle_needs_fresh_token_error(jwt_header, jwt_payload):
    """
    Handle errors when a fresh JWT token is required.

    Args:
        jwt_header (dict): JWT header data.
        jwt_payload (dict): JWT payload data.

    Returns:
        tuple: JSON error response with 401 status code.
    """
    return jsonify({"error": "Fresh token required"}), 401


@app.route("/login", methods=["POST"])
def login():
    """
    Authenticate a user and return a JWT access token.

    Expected JSON payload:
        {
            "username": "user1",
            "password": "password"
        }

    Returns:
        tuple: JSON response containing an access token if credentials are valid,
               otherwise an error response with 401 status code.
    """
    data = request.get_json()
    username = data.get("username")
    password = data.get("password")
    user = users.get(username)

    if not user or not check_password_hash(user["password"], password):
        return jsonify({"error": "Unauthorized"}), 401

    access_token = create_access_token(
        identity=username,
        additional_claims={"role": user["role"]}
    )
    return jsonify({"access_token": access_token})


@app.route("/jwt-protected")
@jwt_required()
def jwt_protected():
    """
    Protected route using JWT Authentication.

    Returns:
        str: Access granted message if JWT token is valid.
    """
    return "JWT Auth: Access Granted"


@app.route("/admin-only")
@jwt_required()
def admin_only():
    """
    Protected route accessible only to admin users.

    The user's role is checked from the JWT claims.

    Returns:
        str: Admin access granted message if the user is admin.
        tuple: JSON error response with 403 status code if user is not admin.
    """
    claims = get_jwt()
    if claims.get("role") != "admin":
        return jsonify({"error": "Admin access required"}), 403
    return "Admin Access: Granted"


if __name__ == "__main__":
    """
    Run the Flask development server.
    """
    app.run(debug=True)
